name: E2E Should Run
description: Outputs true if E2E tests should be run

outputs:
  should-run:
    description: Whether E2E tests should be run
    value: ${{ steps.should-run.outputs.should-run }}

runs:
  using: composite
  steps:
    - name: Should run
      id: should-run
      if: |
        contains(github.event.pull_request.labels.*.name, 'e2e-test') && !contains(github.event.pull_request.labels.*.name, 'blocked') ||
        github.event_name != 'pull_request'
      shell: bash
      run: echo "should-run=true" >> $GITHUB_OUTPUT