name: "Build and push flink image to ghcr.io"
description: "Build and push flink image to ghcr.io"
inputs:
  # restore
  settings-path:
    description: "..."
    default: "./"
    required: true
  read_package_pat:
    description: "PAT for reading packages"
    required: true
  # build
  context:
    description: "Path to context"
    required: true
  dockerfile_path:
    description: ""
    default: dockerfiles/Dockerfile.generic
  environment:
    required: false
    description: "Which environment to build for"
    default: Production
  architecture:
    required: false
    description: "Which architectures to build for"
    default: "linux/amd64,linux/arm64"
  maven-settings-path:
    description: "..."
    default: "./"
    required: true
  jar_name_pattern:
    description: ""
    required: false
  flink_image_version:
    description: ""
    required: false
  # push
  image_name:
    description: "Name of the image to build"
    required: true
  image_tag:
    description: "if set, will be used as tag instead of the default autogenerated tags"
    required: false
    default: ""
  github_run_id:
    description: ""
    required: false
    default: latest
  # upload
  gitlab_token:
    description: ""
    required: false
    default: ""
  push_image:
    description: Should we push the image
    required: false
    default: "true"
  upload_image:
    description: Should we upload the image as an artifact
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Get app version
      shell: bash
      id: vars
      run: echo ::set-output name=app_version::${GITHUB_REF#refs/*/v}

    - uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/maven/maven-restore@main
      with:
        settings-path: ${{ inputs.maven-settings-path }} # location for the settings.xml file
        github_actor: ${{ github.actor }}
        read_package_pat: ${{ inputs.read_package_pat }}

    - name: Build image
      uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/build-image/base@main
      with:
        # restore
        read_package_pat: ${{ inputs.read_package_pat }} # we need this, as GITHUB_TOKEN only have permission to its own repo
        # build
        context: ${{ inputs.context }}
        dockerfile_path: ${{ inputs.dockerfile_path }}
        environment: ${{ inputs.environment }}
        github_run_id: ${{ inputs.github_run_id }}
        architecture: ${{ inputs.architecture }}
        # push
        image_name: ${{ inputs.image_name }}
        image_tag: ${{ inputs.image_tag }}
        # upload
        gitlab_token: ${{ inputs.gitlab_token }}
        push_image: ${{ inputs.push_image }}
        upload_image: ${{ inputs.upload_image }}

        build-args: |
          projectFile=${{ inputs.project_path }}
          assemblyName=${{ inputs.assembly_name }}
          src=${{ inputs.src }}
          jarNamePattern=${{ inputs.jar_name_pattern }}
          flinkImageVersion=${{ inputs.flink_image_version }}
          ENVIRONMENT=${{ inputs.environment }}
          APP_VERSION=${{ steps.vars.outputs.app_version }}
