name: Get Version
description: "Bumps the version in the given file between the given prefix and suffix"

inputs:
  file-path:
    description: "The path to the file with the version"
    required: true
  prefix:
    description: "Some text directly before the version in the file"
    required: false
    default: ""
  suffix:
    description: "Some text directly after the version in the file"
    required: false
    default: ""
outputs:
  version:
    description: "The version found in the specified file"
    value: ${{ steps.get-version.outputs.current-version}}

runs:
  using: composite
  steps:
    - name: "Get version"
      id: get-version
      shell: bash
      run: |
        prefix="${{ inputs.prefix }}"
        suffix="${{ inputs.suffix }}"
        file_path="${{ inputs.file-path }}"

        current_version=$(grep -Po "(?<=$prefix)[0-9]+\.[0-9]+\.[0-9]+(?=$suffix)" $file_path)

        echo "Current version: $current_version"
        echo "current-version=$current_version" >> $GITHUB_OUTPUT