name: "Restore maven dependencies"
description: ""
inputs:
  working-directory:
    description: "..."
    required: false
    default: "."
  github_actor:
    description: ""
    required: true
  read_package_pat:
    description: "..."
    required: true
  repository-path:
    description: "where maven packages are stored"
    default: ".m2"
    required: false

runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ./ # location for the settings.xml file

    - name: Change scope of Flink dependencies from 'compile' to 'provided'.
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: sed -i pom.xml -e 's,<scope>compile</scope>,<scope>provided</scope>,'

    - uses: actions/cache/restore@v3
      with:
        path: ${{ inputs.repository-path }}
        key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          setup-java-${{ runner.os }}-maven-
          setup-java-${{ runner.os }}-

    - name: Restore packages (for caching)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn dependency:go-offline -B -s ./settings.xml -D"maven.repo.local=${{ inputs.repository-path }}/repository"
      env:
        GITHUB_ACTOR: ${{ inputs.github_actor }}
        GITHUB_TOKEN: ${{ inputs.read_package_pat }}

    - uses: actions/cache/save@v3
      with:
        path: ${{ inputs.repository-path }}
        key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
