name: "Restore maven dependencies"
description: ""
inputs:
  working-directory:
    description: "..."
    required: false
    default: "."
  github_actor:
    description: ""
    required: true
  read_package_pat:
    description: "..."
    required: true
  repository-path:
    description: "where maven packages are stored"
    default: ".m2"
    required: false
  java-version:
    description: The version of the Java JDK to use
    default: "17"
    required: false

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"
        settings-path: ./

    - uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.repository-path }}
        key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          setup-java-${{ runner.os }}-maven-
          setup-java-${{ runner.os }}-

    - name: Restore packages (for caching)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn dependency:go-offline -B -s ./settings.xml -D"maven.repo.local=${{ inputs.repository-path }}/repository"
      env:
        GITHUB_ACTOR: ${{ inputs.github_actor }}
        GITHUB_TOKEN: ${{ inputs.read_package_pat }}

    - uses: actions/cache/save@v4
      with:
        path: ${{ inputs.repository-path }}
        key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
