name: Docker Create Release Branch

on:
  workflow_call:
    inputs:
      image-name:
        description: The name of the project. If this is non-empty, the release branch will be called 'release/<project-name>-vX.Y>' Leave this empty if you only have a single project in the repository
        required: false
        type: string
      dockerfile-path:
        description: The path to the Dockerfile
        required: true
        type: string
      bump-type:
        description: Whether to create a minor or a major release
        required: true
        type: string
    secrets:
      PAT:
        description: A personal access token with permission to push to all branches
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }} # for pushing to a protected branch

      - name: Bump major version
        if: ${{ inputs.bump-type == 'major' }}
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/bump-version@main
        with:
          file-path: ${{ inputs.dockerfile-path }}
          prefix: 'LABEL version=\"'
          suffix: '\"'
          bump-type: major

      - name: Get project version
        id: get-version
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/get-version@main
        with:
          file-path: ${{ inputs.dockerfile-path }}
          prefix: 'LABEL version=\"'
          suffix: '\"'

      - name: Create release branch
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/create-release-branch@main
        with:
          project-name: ${{ inputs.image-name }}
          release-version: ${{ steps.get-version.outputs.version }}

      - name: Bump minor version
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/bump-version@main
        with:
          file-path: ${{ inputs.dockerfile-path }}
          prefix: 'LABEL version=\"'
          suffix: '\"'
          bump-type: minor

      - name: Create pull request to main
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          author: cheetahbot <cheetahbot@users.noreply.github.com>
          committer: cheetahbot <cheetahbot@users.noreply.github.com>
          token: ${{secrets.PAT}}
          branch: auto-bump-patch
          base: ${{github.ref_name}}
          labels: automerge
          delete-branch: true
          commit-message: "Bump release branch patch version"
          title: bump/patch