name: E2E Should Run

on:
  workflow_call:
    outputs:
      should-run:
        description: Whether E2E tests should be run
        value: ${{ jobs.should-run.outputs.should-run }}

jobs:
  should-run:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.should-run.outputs.should-run }}
    steps:
      - name: Should run
        id: should-run
        if: |
          contains(github.event.pull_request.labels.*.name, 'e2e-test') && !contains(github.event.pull_request.labels.*.name, 'blocked') ||
          github.event_name != 'pull_request'
        shell: bash
        run: echo "should-run=true" >> $GITHUB_OUTPUT