name: Helm Create Snapshot Call

on:
  workflow_call:
    inputs:
      helm-chart:
        type: string
        description: Which hlem chart to create a snapshot for
        required: true
    secrets:
      PAT:
        description: Token with read/write packages and repo access
        required: true

jobs:
  create-snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_PUSH_PAT || github.token }}

      - name: Build and publish snapshot package
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/helm/helm-publish@main
        with:
          package-suffix: "SNAPSHOT${{github.run_number}}"
          PAT: ${{ secrets.PAT }}
          chart: ${{inputs.helm-chart}}
