name: Helm Create Release Call
on:
  workflow_call:
    inputs:
      helm-chart:
        type: string
        description: Which hlem chart to create a release for
        required: true

    secrets:
      PAT:
        description: Token with read/write packages and repo access
        required: true

jobs:
  verify-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: "Success"
        if: ${{ startsWith(github.ref_name, 'release/') }}
        run: |
          exit 0

      - name: "Error"
        if: ${{ !startsWith(github.ref_name, 'release/') }}
        run: |
          exit 1

  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: verify-release-branch

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || github.token }}

      - name: Configure Git
        run: |
          git config user.name "cheetahbot"
          git config user.email "cheetahbot@users.noreply.github.com"

      - name: Build and release package
        id: build-and-release
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/helm/helm-publish@main
        with:
          PAT: ${{ secrets.PAT }}
          package-suffix: ""
          chart: ${{ inputs.helm-chart }}

      - name: Generate Checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: "./${{ inputs.helm-chart }}-${{steps.build-and-release.outputs.version}}.tgz"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{inputs.helm-chart}}-v${{ steps.build-and-release.outputs.version }}
          files: checksum.txt
          target_commitish: ${{ github.ref }}

      - name: Bump version
        id: bump-version
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/bump-version@main
        with:
          file-path: ./charts/${{ inputs.helm-chart}}/Chart.yaml
          prefix: "version: "
          bump-type: "patch"

      -  name: Bump ReadMe
         uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/helm/bump-readme@main
         with:
           file-path: ./charts/${{ inputs.helm-chart}}/README.md
           version: ${{ steps.bump-version.outputs.new-version }}

      - name: Commit minor version bump
        id: commit
        uses: qoomon/actions--create-commit@v1
        with:
          message: Bump minor version to keep version ahead of all releases
          allow-empty: true

      - if: ${{ steps.commit.outputs.commit }}
        run: git push