name: Helm Create Release Branch
on:
  workflow_call:
    inputs:
      helm-chart:
        type: string
        description: Which hlem chart to create a release branch for
        required: true

      bump-type:
        type: string
        description: Which type of update? patch, minor or major
        default: "minor"
        required: false

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "cheetahbot"
          git config user.email "cheetahbot@users.noreply.github.com"

      - name: Read Helm Chart
        id: chart
        uses: jacobtomlinson/gha-read-helm-chart@0.1.3
        with:
          path: ./charts/${{ inputs.helm-chart}}

      - name: Bump major version
        if: ${{inputs.bump-type == 'major'}}
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/bump-version@main
        with:
          file-path: ./charts/${{ inputs.helm-chart }}/Chart.yaml
          prefix: "version: "
          bump-type: "major"

      - name: Print outputs
        run: |
          echo "Name - ${{ steps.chart.outputs.name }}"
          echo "Version - ${{ steps.chart.outputs.version }}"
          echo "App Version - ${{ steps.chart.outputs.appVersion }}"

      - name: Create release branch
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/create-release-branch@main
        with:
          release-version: ${{steps.chart.outputs.version}}
          project-name: ${{steps.chart.outputs.name}}

      - name: Bump version
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/bump-version@main
        with:
          file-path: ./charts/${{ inputs.helm-chart}}/Chart.yaml
          prefix: "version: "
          bump-type: "minor"

      - name: Commit version bump
        run: |
          git add ./charts/${{ inputs.helm-chart}}
          git commit -m "Bump minor version to keep snapshot version ahead"
          git push
